### Alert Manager Configuration

```
global:
  resolve_timeout: 5m
  smtp_require_tls: false

route:
  receiver: 'all-receiver'
  group_by: ['alertname', 'instance']
  group_wait: 30s
  group_interval: 10m
  repeat_interval: 720h
  routes:
    - match:
        alertname: 'Customer info data shipper'
      receiver: 'critical-alert-receiver'

receivers:
  - name: 'all-receiver'
    email_configs:
      - to: 'digital-platform-support@banglalink.net'
        smarthost: 172.16.7.183:25
        from: 'blmonitor@banglalink.net'
        send_resolved: true
    webhook_configs:
      - send_resolved: true
        url: 'http://172.16.11.237:2000/_dynamicwebhook/banglalinkdigitalcomm.webhook.office.com/webhookb2/366d3cac-f9c3-44c6-acfe-fc7727fa5400@ac33f407-5ccd-46ec-9eef-f4e65ee9c29a/IncomingWebhook/33416308092047d582e2d8f63f860866/52c02b6c-e572-4d01-b528-59336c7a678d/V2rzR6ddU4O_Oi3WnZ6h-1Mhlr7VE57IW9tahYB79mTV81'
        #url: 'http://172.16.11.237:2000/alert'


  - name: 'critical-alert-receiver'
    email_configs:
      - to: 'tahsin.abrar@banglalink.net'
        smarthost: 172.16.7.183:25
        from: 'blmonitor@banglalink.net'
        send_resolved: true
      - to: 'sourav.sarker@banglalink.net'
        smarthost: 172.16.7.183:25
        from: 'blmonitor@banglalink.net'
        send_resolved: true
      - to: 'digital-platform-support@banglalink.net'
        smarthost: 172.16.7.183:25
        from: 'blmonitor@banglalink.net'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']

```